/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ISmartInvoiceFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "create"
      | "createDeterministic"
      | "predictDeterministicAddress"
      | "resolutionRateOf"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "create",
    values: [AddressLike, BigNumberish[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDeterministic",
    values: [AddressLike, BigNumberish[], BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predictDeterministicAddress",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolutionRateOf",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createDeterministic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictDeterministicAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolutionRateOf",
    data: BytesLike
  ): Result;
}

export interface ISmartInvoiceFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ISmartInvoiceFactory;
  waitForDeployment(): Promise<this>;

  interface: ISmartInvoiceFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  create: TypedContractMethod<
    [
      _recipient: AddressLike,
      _amounts: BigNumberish[],
      _data: BytesLike,
      _type: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  createDeterministic: TypedContractMethod<
    [
      _recipient: AddressLike,
      _amounts: BigNumberish[],
      _data: BytesLike,
      _type: BytesLike,
      _salt: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  predictDeterministicAddress: TypedContractMethod<
    [_type: BytesLike, _salt: BytesLike],
    [string],
    "nonpayable"
  >;

  resolutionRateOf: TypedContractMethod<
    [_resolver: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "create"
  ): TypedContractMethod<
    [
      _recipient: AddressLike,
      _amounts: BigNumberish[],
      _data: BytesLike,
      _type: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDeterministic"
  ): TypedContractMethod<
    [
      _recipient: AddressLike,
      _amounts: BigNumberish[],
      _data: BytesLike,
      _type: BytesLike,
      _salt: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "predictDeterministicAddress"
  ): TypedContractMethod<
    [_type: BytesLike, _salt: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolutionRateOf"
  ): TypedContractMethod<[_resolver: AddressLike], [bigint], "view">;

  filters: {};
}
