/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ISmartInvoiceInterface extends Interface {
  getFunction(
    nameOrSignature: "init" | "init(address,uint256[],bytes)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "init",
    values: [AddressLike, BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "init(address,uint256[],bytes)",
    values: [AddressLike, BigNumberish[], BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "init(address,uint256[],bytes)",
    data: BytesLike
  ): Result;
}

export interface ISmartInvoice extends BaseContract {
  connect(runner?: ContractRunner | null): ISmartInvoice;
  waitForDeployment(): Promise<this>;

  interface: ISmartInvoiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  init: TypedContractMethod<
    [_recipient: AddressLike, _amounts: BigNumberish[], _data: BytesLike],
    [void],
    "nonpayable"
  >;

  "init(address,uint256[],bytes)": TypedContractMethod<
    [_recipient: AddressLike, _amounts: BigNumberish[], _data: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "init"
  ): TypedContractMethod<
    [_recipient: AddressLike, _amounts: BigNumberish[], _data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "init(address,uint256[],bytes)"
  ): TypedContractMethod<
    [_recipient: AddressLike, _amounts: BigNumberish[], _data: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
