/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IArbitrable, IArbitrableInterface } from "../IArbitrable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_arbitrator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_disputeID",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_ruling",
        type: "uint256",
      },
    ],
    name: "Ruling",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_disputeID",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_ruling",
        type: "uint256",
      },
    ],
    name: "rule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IArbitrable__factory {
  static readonly abi = _abi;
  static createInterface(): IArbitrableInterface {
    return new Interface(_abi) as IArbitrableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IArbitrable {
    return new Contract(address, _abi, runner) as unknown as IArbitrable;
  }
}
