/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ISmartInvoice, ISmartInvoiceInterface } from "../ISmartInvoice";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_amounts",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISmartInvoice__factory {
  static readonly abi = _abi;
  static createInterface(): ISmartInvoiceInterface {
    return new Interface(_abi) as ISmartInvoiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISmartInvoice {
    return new Contract(address, _abi, runner) as unknown as ISmartInvoice;
  }
}
